project:
  type: website
  output-dir: docs

website:
  title: "IFAR"
  favicon: /img/IFARCover_small.jpg
  site-url: https://derekogle.com/IFAR/
  repo-url: https://github.com/droglenc/IFAR
  repo-actions: []
  navbar:
    title: "Introductory Fisheries Analyses with R by Derek H. Ogle"
    background: "#2B0828"
    foreground: white
  search: false
  page-footer:
    background: "#2B0828"
    foreground: white
    left: "Copyright 2019, Derek H. Ogle"
    right:
      - icon: github
        href: https://github.com/droglenc/IFAR
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/fishR_ogle
        aria-label: Twitter
  comments: false
  open-graph: true
format:
  html:
    theme: [litera, helpers/custom.scss]
    css: helpers/styles.css
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    title-block-banner: false
    toc: true
highlight-style: github
date-format: medium
execute: 
  freeze: auto
