<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Derek H. Ogle">

<title>IFAR - Maturity Analyses</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<link href="..//img/IFARCover_small.jpg" rel="icon" type="image/jpeg">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../helpers/styles.css">
<meta property="og:title" content="IFAR - Maturity Analyses">
<meta property="og:description" content="The length-, weight-, or age-at-maturity is important to monitor for fish populations because these metrics are closely tied to reproductive potential and respond to changes in inter- and…">
<meta property="og:site-name" content="IFAR">
<meta name="citation_title" content="Maturity Analyses">
<meta name="citation_author" content="Derek H. Ogle">
<meta name="citation_fulltext_html_url" content="https://droglenc.github.io/IFAR//maturity.html">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Introductory Fisheries Analyses with R;,citation_author=Derek H. Ogle;,citation_publication_date=2016;,citation_cover_date=2016;,citation_year=2016;,citation_fulltext_html_url=http://derekogle.com/IFAR/;">
<meta name="citation_reference" content="citation_title=On the Dynamics of Exploited Fish Populations;,citation_author=R. J. H. Beverton;,citation_author=S. J. Holt;,citation_publication_date=1957;,citation_cover_date=1957;,citation_year=1957;,citation_volume=19;,citation_series_title=Fisheries Investigations (Series 2);">
<meta name="citation_reference" content="citation_title=Standard intercepts for calculating lengths from scale measurements for some centrarchid and percid fishes;,citation_author=K. D. Carlander;,citation_publication_date=1982;,citation_cover_date=1982;,citation_year=1982;,citation_volume=111;,citation_journal_title=Transactions of the American Fisheries Society;">
<meta name="citation_reference" content="citation_title=Minpack.lm: R Interface to the Levenberg-Marquardt Nonlinear Least-Squares Algorithm Found in MINPACK, Plus Support for Bounds;,citation_author=Timur V. Elzhov;,citation_author=Katharine M. Mullen;,citation_author=Andrej-Nikolai Spiess;,citation_author=Ben M. Bolker;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_fulltext_html_url=http://CRAN.R-project.org/package=minpack.lm;">
<meta name="citation_reference" content="citation_title=Are growth parameters estimated from tagging and age-length data comparable?;,citation_author=R. I. C. C. Francis;,citation_publication_date=1988;,citation_cover_date=1988;,citation_year=1988;,citation_volume=45;,citation_journal_title=Canadian Journal of Fisheries and Aquatic Sciences;">
<meta name="citation_reference" content="citation_title=Back-calculation of fish length: A critical review;,citation_author=R. I. C. C. Francis;,citation_publication_date=1990;,citation_cover_date=1990;,citation_year=1990;,citation_volume=36;,citation_journal_title=Journal of Fish Biology;">
<meta name="citation_reference" content="citation_title=Growth of the spring salmon;,citation_author=C. McL. Fraser;,citation_publication_date=1916;,citation_cover_date=1916;,citation_year=1916;,citation_volume=1915;,citation_journal_title=Transactions of the Pacific Fisheries Society;">
<meta name="citation_reference" content="citation_title=On the nature of the function expressive of the law of human mortality and on a new mode of determining the value of life contingencies.;,citation_author=B. Gompertz;,citation_publication_date=1825;,citation_cover_date=1825;,citation_year=1825;,citation_volume=115;,citation_journal_title=Philosophical Transactions of the Royal Society of London;">
<meta name="citation_reference" content="citation_title=Dates and times made easy with lubridate;,citation_author=Garrett Grolemund;,citation_author=Hadley Wickham;,citation_publication_date=2011;,citation_cover_date=2011;,citation_year=2011;,citation_fulltext_html_url=http://www.jstatsoft.org/v40/i03/;,citation_issue=3;,citation_volume=40;,citation_journal_title=Journal of Statistical Software;">
<meta name="citation_reference" content="citation_title=nls2: Non-Linear Regression with Brute Force;,citation_author=G. Grothendieck;,citation_publication_date=2013;,citation_cover_date=2013;,citation_year=2013;,citation_fulltext_html_url=http://CRAN.R-project.org/package=nls2;">
<meta name="citation_reference" content="citation_title=On the methods used in the Herring-investigations.;,citation_author=E. Lea;,citation_publication_date=1910;,citation_cover_date=1910;,citation_year=1910;,citation_issue=1;,citation_volume=108;,citation_journal_title=Publ. Circonst. Cons. perm. int. Explor. Mer;">
<meta name="citation_reference" content="citation_title=A review of the methods of age and growth determination in fishes by means of scales.;,citation_author=R. M. Lee;,citation_publication_date=1920;,citation_cover_date=1920;,citation_year=1920;,citation_issue=(2);,citation_volume=4;,citation_journal_title=Fisheries Investigations, London Series 2;">
<meta name="citation_reference" content="citation_title=Analysis and comparison of fish growth from small samples of length-at-age data: Detection of sexual dimorphism in Eurasian Perch as an example;,citation_author=W. M. Mooij;,citation_author=J. M. Van Rooij;,citation_author=S. Wijnhoven;,citation_publication_date=1999;,citation_cover_date=1999;,citation_year=1999;,citation_volume=128;,citation_journal_title=Transactions of the American Fisheries Society;">
<meta name="citation_reference" content="citation_title=Fitting curves to data using nonlinear regression: A practical and nonmathematical review;,citation_abstract=Many types of data are best analyzed by fitting a curve using nonlinear regression, and computer programs that perform these calculations are readily available. Like every scientific technique, however, a nonlinear regression program can produce misleading results when used inappropriately. This article reviews the use of nonlinear regression in a practical and nonmathematical manner to answer the following questions: Why is nonlinear regression superior to linear regression of transformed data? How does nonlinear regression differ from polynomial regression and cubic spline? How do nonlinear regression programs work? What choices must an investigator make before performing nonlinear regression? What do the final results mean? How can two sets of data or two fits to one set of data be compared? What problems can cause the results to be wrong? This review is designed to demystify nonlinear regression so that both its power and its limitations will be appreciated.;,citation_author=H. J. Motulsky;,citation_author=L. A. Ransnas;,citation_publication_date=1987;,citation_cover_date=1987;,citation_year=1987;,citation_fulltext_html_url=http://www.fasebj.org/content/1/5/365.full.pdf+html;,citation_volume=1;,citation_journal_title=The Federation of American Societies for Experimental Biology Journal;">
<meta name="citation_reference" content="citation_title=Nlmrt: Functions for Nonlinear Least Squares Solutions;,citation_author=John C. Nash;,citation_publication_date=2014;,citation_cover_date=2014;,citation_year=2014;,citation_fulltext_html_url=http://CRAN.R-project.org/package=nlmrt;">
<meta name="citation_reference" content="citation_title=Ruffe length-weight relationships with a proposed standard weight equation;,citation_author=D. H. Ogle;,citation_author=I. J. Winfield;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_fulltext_html_url=http://www.tandfonline.com/doi/abs/10.1577/M08-176.1#.U6ojzvldV8E;,citation_volume=29;,citation_journal_title=North American Journal of Fisheries Management;">
<meta name="citation_reference" content="citation_title=Methods for Assessing Fish Populations;,citation_author=Kevin L. Pope;,citation_author=Steve E. Lochmann;,citation_author=Michael K. Young;,citation_editor=W. A. Hubert;,citation_editor=M. C. Quist;,citation_publication_date=2010;,citation_cover_date=2010;,citation_year=2010;,citation_inbook_title=Inland Fisheries Management in North America;">
<meta name="citation_reference" content="citation_title=A flexible growth function for empirical use;,citation_author=F. J. Richards;,citation_publication_date=1959;,citation_cover_date=1959;,citation_year=1959;,citation_volume=10;,citation_journal_title=Journal of Experimental Botany;">
<meta name="citation_reference" content="citation_title=Computation and Interpretation of Biological Statistics of Fish Populations;,citation_author=W. E. Ricker;,citation_publication_date=1975;,citation_cover_date=1975;,citation_year=1975;,citation_technical_report_institution=Bulletin of the Fisheries Research Board of Canada;,citation_technical_report_number=Bulletin 191;">
<meta name="citation_reference" content="citation_title=A versatile growth model with statistically stable parameters;,citation_author=J. Schnute;,citation_publication_date=1981;,citation_cover_date=1981;,citation_year=1981;,citation_volume=38;,citation_journal_title=Canadian Journal of Fisheries and Aquatic Sciences;">
<meta name="citation_reference" content="citation_title=A unified approach to the analysis of fish growth, maturity, and survivorship data;,citation_author=J. T. Schnute;,citation_author=L. J. Richards;,citation_publication_date=1990;,citation_cover_date=1990;,citation_year=1990;,citation_volume=47;,citation_journal_title=Canadian Journal of Fisheries and Aquatic Sciences;">
<meta name="citation_reference" content="citation_title=The back-calculation of fish growth from otoliths;,citation_author=L. Vigliola;,citation_author=M. G. Meekan;,citation_editor=B. S. Green;,citation_editor=B. D. Mapstone;,citation_editor=G. Carlos;,citation_editor=G. A. Begg;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_inbook_title=Tropical Fish Otoliths: Information for Assessment, Management, and Ecology;,citation_series_title=Reviews: Methods and Technologies in Fish Biology and Fisheries;">
<meta name="citation_reference" content="citation_title=A quantitative theory of organic growth (inquiries on growth laws II);,citation_author=L. Bertalanffy;,citation_publication_date=1938;,citation_cover_date=1938;,citation_year=1938;,citation_volume=10;,citation_journal_title=Human Biology;">
<meta name="citation_reference" content="citation_title=Using hard-part increment data to estimate age and environmental effects;,citation_author=S. Weisberg;,citation_publication_date=1993;,citation_cover_date=1993;,citation_year=1993;,citation_issue=6;,citation_volume=50;,citation_journal_title=Canadian Journal of Fisheries and Aquatic Sciences;">
<meta name="citation_reference" content="citation_title=Interpretation of body-scale regression for computing body length of fish.;,citation_author=R. R. Whitney;,citation_author=K. D. Carlander;,citation_publication_date=1956;,citation_cover_date=1956;,citation_year=1956;,citation_volume=20;,citation_journal_title=Journal of Wildlife Management;">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Introductory Fisheries Analyses with R by Derek H. Ogle</span>
    </a>
  </div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup" id="toc-setup" class="nav-link active" data-scroll-target="#setup">Setup</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  </ul></li>
  <li><a href="#maturity-data" id="toc-maturity-data" class="nav-link" data-scroll-target="#maturity-data">Maturity Data</a></li>
  <li><a href="#modeling-with-raw-data" id="toc-modeling-with-raw-data" class="nav-link" data-scroll-target="#modeling-with-raw-data">Modeling with Raw Data</a>
  <ul class="collapse">
  <li><a href="#fitting-the-logistic-regression-model" id="toc-fitting-the-logistic-regression-model" class="nav-link" data-scroll-target="#fitting-the-logistic-regression-model">Fitting the Logistic Regression Model</a></li>
  <li><a href="#predicted-probability-of-being-mature" id="toc-predicted-probability-of-being-mature" class="nav-link" data-scroll-target="#predicted-probability-of-being-mature">Predicted Probability of Being Mature</a></li>
  <li><a href="#a-summary-plot" id="toc-a-summary-plot" class="nav-link" data-scroll-target="#a-summary-plot">A Summary Plot</a></li>
  <li><a href="#length--or-age-at-maturity" id="toc-length--or-age-at-maturity" class="nav-link" data-scroll-target="#length--or-age-at-maturity">Length- or Age-at-Maturity</a></li>
  </ul></li>
  <li><a href="#modeling-with-summarized-data" id="toc-modeling-with-summarized-data" class="nav-link" data-scroll-target="#modeling-with-summarized-data">Modeling with Summarized Data</a></li>
  <li><a href="#comparing-logistic-regressions-between-groups" id="toc-comparing-logistic-regressions-between-groups" class="nav-link" data-scroll-target="#comparing-logistic-regressions-between-groups">Comparing Logistic Regressions Between Groups</a>
  <ul class="collapse">
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting">Model Fitting</a></li>
  <li><a href="#comparing-lengths--or-ages-at-maturity" id="toc-comparing-lengths--or-ages-at-maturity" class="nav-link" data-scroll-target="#comparing-lengths--or-ages-at-maturity">Comparing Lengths- or Ages-at-Maturity</a></li>
  <li><a href="#a-summary-plot-1" id="toc-a-summary-plot-1" class="nav-link" data-scroll-target="#a-summary-plot-1">A Summary Plot</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Maturity Analyses</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Derek H. Ogle </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>The length-, weight-, or age-at-maturity is important to monitor for fish populations because these metrics are closely tied to reproductive potential and respond to changes in inter- and intra-specific densities and resource availability <span class="citation" data-cites="pope_methods_2010">(<a href="#ref-pope_methods_2010" role="doc-biblioref">Pope et al. 2010</a>)</span>. Methods for modeling the relationship between maturity stage and length is demonstrated in this supplement. Results from these modeled relationships are then used to calculate metrics such as length at 50% maturity. These methods extend directly to use with age or weight data.</p>
<section id="setup" class="level1 page-columns page-full">
<h1>Setup</h1>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Functions used in this supplement require the following packages. Also note that one function from <code>lubridate</code> and two functions from <code>car</code> are used below with <code>::</code> so that the whole packages do not need to be loaded.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(FSA)      <span class="co"># for headtail()</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)    <span class="co"># for select(), mutate(), filter()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">

</div>
</section>
<section id="data" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<div class="page-columns page-full"><p>The total length (<code>length</code>; to the nearest cm), <code>age</code> (years), and <code>maturity</code> (<code>Immature</code> and <code>Mature</code>) state of female Yelloweye Rockfish (<em>Sebastes rubberimus</em>) collected from along the Oregon coast are recorded in <a href="https://fishr-core-team.github.io/FSAdata/reference/YERockFish.html">YERockFish.csv</a>.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The <code>stage</code> variable was removed to minimize output below.</p><div class="no-row-height column-margin column-container"><li id="fn1"><p><sup>1</sup>&nbsp;Download data with CSV link on the linked page.</p></li></div></div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/fishr-core-team/FSAdata/master/data-raw/YERockfish.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>stage)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  'data.frame':  158 obs. of  4 variables:
#R|   $ date    : chr  "9/2/2003" "10/7/2002" "7/18/2000" "6/11/2001" ...
#R|   $ length  : int  31 32 32 32 32 33 33 34 34 34 ...
#R|   $ age     : int  10 6 11 11 13 9 10 8 10 11 ...
#R|   $ maturity: chr  "Immature" "Immature" "Immature" "Immature" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">headtail</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|           date length age maturity
#R|  1    9/2/2003     31  10 Immature
#R|  2   10/7/2002     32   6 Immature
#R|  3   7/18/2000     32  11 Immature
#R|  156 8/18/2002     67  50   Mature
#R|  157 10/7/2002     68  88   Mature
#R|  158 4/23/2001     70  66   Mature</code></pre>
</div>
</div>
<div class="page-columns page-full"><p>For use with <code>glm()</code> below, the maturity variable must be a <strong>factor</strong> variable, not the character variable that it is currently in <code>df</code>. Variables may be converted to factors with <code>factor()</code>. I use <code>levels=</code> to make sure that the level that represents “being mature” is listed second.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn2"><p><sup>2</sup>&nbsp;By default, the levels are created in alphabetical order, which would have worked correctly in this case.</p></li></div></div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">maturity=</span><span class="fu">factor</span>(maturity,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"Immature"</span>,<span class="st">"Mature"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The date of capture was also recorded. A new variable that indicates whether the fish was captured before 2002 or in 2002 and after is needed for use in a later example that compares the relationship between maturity and length between two groups. This conversion requires that <code>date</code> be converted to a format that R will recognize as a date. The <code>as.POSIXct()</code> function does this conversion, taking the original dates as its first argument. Additionally, a string is given to <code>format=</code> that describes the format of the dates in the original variable. The codes that may be used in this string are described in <code>?strptime</code>. Common codes used with fisheries data are</p>
<ul>
<li><code>%m</code>: month as a number,</li>
<li><code>%b</code>: month as an abbreviated name (e.g., <code>Jan</code>, <code>Feb</code>),</li>
<li><code>%d</code>: day of the month,</li>
<li><code>%Y</code>: four-digit year (e.g., <code>2015</code>), and</li>
<li><code>%y</code>: two-digit (i.e., without the century) year (e.g., <code>15</code>).</li>
</ul>
<p>These format codes are separated by the characters that separate the fields in the original date variable (e.g., <code>/</code>, <code>-</code>).</p>
<p>An examination of <code>date</code> above shows that the dates are in month as a number, day of the month, and four digit year format separated by “forward slashes.” Thus, <code>date</code> is converted below to a date format that R will recognize.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date=</span><span class="fu">as.POSIXct</span>(date,<span class="at">format=</span><span class="st">"%m/%d/%Y"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  'data.frame':  158 obs. of  4 variables:
#R|   $ date    : POSIXct, format: "2003-09-02" "2002-10-07" ...
#R|   $ length  : int  31 32 32 32 32 33 33 34 34 34 ...
#R|   $ age     : int  10 6 11 11 13 9 10 8 10 11 ...
#R|   $ maturity: Factor w/ 2 levels "Immature","Mature": 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>The year of capture may then be extracted from <code>date</code> with <code>year()</code> from <code>lubridate</code>. Note that the month could be extracted with <code>month()</code>, day of the month with <code>mday()</code>, and day of the year (1-366) with <code>yday()</code>. A variable (<code>era</code>) that indicates the era (<code>pre-2002</code> or <code>2002 and after</code>) is then added to the data frame as a factor.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year=</span>lubridate<span class="sc">::</span><span class="fu">year</span>(date),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">era=</span><span class="fu">ifelse</span>(year<span class="sc">&lt;</span><span class="dv">2002</span>,<span class="st">"pre-2002"</span>,<span class="st">"2002 and after"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">era=</span><span class="fu">factor</span>(era,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"pre-2002"</span>,<span class="st">"2002 and after"</span>)))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">headtail</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|            date length age maturity year            era
#R|  1   2003-09-02     31  10 Immature 2003 2002 and after
#R|  2   2002-10-07     32   6 Immature 2002 2002 and after
#R|  3   2000-07-18     32  11 Immature 2000       pre-2002
#R|  156 2002-08-18     67  50   Mature 2002 2002 and after
#R|  157 2002-10-07     68  88   Mature 2002 2002 and after
#R|  158 2001-04-23     70  66   Mature 2001       pre-2002</code></pre>
</div>
</div>
<p>Finally, <code>maturity</code> was not recorded for several individuals, which were removed from further analysis.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(maturity))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>&nbsp;</p>
</section>
</section>
<section id="maturity-data" class="level1 page-columns page-full">
<h1>Maturity Data</h1>
<p>Raw maturity data generally consists of a maturity statement (either “mature” or “immature”), size (length or weight), age, sex, and other variables as needed (e.g., capture date, capture location) recorded for individual fish. The maturity variable may need to be derived from more specific data about the “stage of maturation” recorded for each fish. Often, maturity will be recorded as a dummy or indicator variable – “0” for immature and “1” for mature – but this is not required for most modern software. Sex is an important variable to record as maturity should be analyzed separately for each sex <span class="citation" data-cites="pope_methods_2010">(<a href="#ref-pope_methods_2010" role="doc-biblioref">Pope et al. 2010</a>)</span>.</p>
<p>Summarized maturity data consists of the proportion of individuals that are mature within each age or length category. Age categories are generally the recorded ages, whereas recorded lengths are often categorized into bins. Age or length categories should be as narrow as possible but include enough individuals such that the proportion mature in each bin is reliably estimated.</p>
<p>In this supplement, the total length of the Rockfish was measured to the nearest cm. Length categories that were 2 cm were chosen to summarize the data to provide reasonable sample sizes (<span class="math inline">\(&gt;10\)</span> fish) in the length ranges where the proportion of mature fish is most rapidly changing. These length categories are added to the data.frame with <code>lencat()</code> below (as described in Chapter 2 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lcat2=</span><span class="fu">lencat</span>(length,<span class="at">w=</span><span class="dv">2</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">headtail</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|            date length age maturity year            era lcat2
#R|  1   2003-09-02     31  10 Immature 2003 2002 and after    30
#R|  2   2002-10-07     32   6 Immature 2002 2002 and after    32
#R|  3   2000-07-18     32  11 Immature 2000       pre-2002    32
#R|  146 2002-08-18     67  50   Mature 2002 2002 and after    66
#R|  147 2002-10-07     68  88   Mature 2002 2002 and after    68
#R|  148 2001-04-23     70  66   Mature 2001       pre-2002    70</code></pre>
</div>
</div>
<p>The frequency of mature and immature fish in each length category is computed with <code>xtabs()</code> below. The raw frequencies are converted to “row proportions” with <code>prop.table()</code> to see the proportion of fish within each length category that are mature. Finally, a plot of the proportion of mature fish is constructed (<a href="#fig-sumLength">Figure&nbsp;1</a>).</p>
<div class="cell page-columns page-full" data-layout-align="center" data-par1="true">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>freq <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="sc">~</span>lcat2<span class="sc">+</span>maturity,<span class="at">data=</span>df)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>props <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(freq,<span class="at">margin=</span><span class="dv">1</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(props,<span class="dv">3</span>)   <span class="co"># for display only</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|       maturity
#R|  lcat2 Immature Mature
#R|     30    1.000  0.000
#R|     32    1.000  0.000
#R|     34    1.000  0.000
#R|     36    0.556  0.444
#R|     38    0.625  0.375
#R|     40    0.333  0.667
#R|     42    0.077  0.923
#R|     44    0.077  0.923
#R|     46    0.036  0.964
#R|     48    0.062  0.938
#R|     50    0.000  1.000
#R|     52    0.000  1.000
#R|     54    0.000  1.000
#R|     56    0.000  1.000
#R|     58    0.000  1.000
#R|     60    0.000  1.000
#R|     62    0.000  1.000
#R|     64    0.000  1.000
#R|     66    0.000  1.000
#R|     68    0.000  1.000
#R|     70    0.000  1.000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(props[,<span class="st">"Mature"</span>]<span class="sc">~</span><span class="fu">as.numeric</span>(<span class="fu">rownames</span>(props)),<span class="at">pch=</span><span class="dv">19</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Total Length (cm)"</span>,<span class="at">ylab=</span><span class="st">"Proportion Mature"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-sumLength" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="maturity_files/figure-html/fig-sumLength-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption margin-caption">Figure&nbsp;1: Proportion of female Yelloweye Rockfish that were mature in each 2-cm length category.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>These results show that the percentage of mature female Yellow Rockfish increases quickly between 34 and 42 cm.</p>
<p>&nbsp;</p>
</section>
<section id="modeling-with-raw-data" class="level1 page-columns page-full">
<h1>Modeling with Raw Data</h1>
<section id="fitting-the-logistic-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-logistic-regression-model">Fitting the Logistic Regression Model</h2>
<p>Raw maturity data is generally summarized with a logistic regression. A logistic regression is conducted with a binomial response variable and, generally, a quantitative explanatory variable. The relationship between the probability of “success” (<span class="math inline">\(p\)</span>) and the explanatory variable (length or age) is generally not linear (primarily due to the constraint that the probability is between 0 and 1). This relationship can be linearized by first transforming <span class="math inline">\(p\)</span> to the odds (i.e., <span class="math inline">\(\frac{p}{1-p}\)</span>). The odds related the probability of “successes” to “failures.” For example, an odds of 1 indicates that there is an equal probability of success and failure, whereas an odds of 3 indicates that the probability of success is three times the probability of failure.</p>
<p>The transformation to a linear relationship is completed by computing the logarithm of the odds (i.e., <span class="math inline">\(log(\frac{p}{1-p})\)</span>). The complete transformation from <span class="math inline">\(p\)</span> to <span class="math inline">\(log(\frac{p}{1-p})\)</span> is called the <em>logit</em> transformation.</p>
<p>Thus, the linear model in a logistic regression models the log odds as a function of an explanatory variable, <span class="math inline">\(X\)</span>, with</p>
<p><span id="eq-LogisticModel"><span class="math display">\[ log\left(\frac{p}{1-p}\right) = \alpha + \beta_{1}X  \tag{1}\]</span></span></p>
<p>In maturity analyses, the logistic regression is used to model the log odds of being mature as a function of either length or age. It will be shown later in this supplement how the log odds of being mature are back-transformed to the probability of being mature.</p>
<p>Logistic regressions are fit with <code>glm()</code>, rather than the <code>lm()</code> used in <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>. For a logistic regression the first argument to <code>glm()</code> is a formula of the form <code>factor~quant</code> where <code>factor</code> and <code>quant</code> generically represent factor and quantitative variables, respectively. The data.frame that contains <code>factor</code> and <code>quant</code> is given to <code>data=</code>. Finally, <code>glm()</code> is forced to use the logit transformation and fit a logistic regression by including <code>family=binomial</code>. For example, the <code>glm()</code> code below will model the log odds of being mature as a function of the length of the Rockfish.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>glm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(maturity<span class="sc">~</span>length,<span class="at">data=</span>df,<span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Parameter estimates are extracted from the <code>glm()</code> object with <code>coef()</code>. Confidence intervals for the parameters of a logistic regression are best estimated with bootstrapping (rather than normal theory). Bootstrapping is performed with <code>bootCase()</code> from <code>car</code> as described in Chapter 12 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>.</p>
<div class="cell" data-layout-align="center" data-hash="maturity_cache/html/unnamed-chunk-11_c75d27ec729c8f37a4e31f8f80e230e9">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>bcL <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">Boot</span>(glm1)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">Ests=</span><span class="fu">coef</span>(glm1),<span class="fu">confint</span>(bcL))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|                     Ests       2.5 %      97.5 %
#R|  (Intercept) -16.9482593 -24.6251636 -10.9477496
#R|  length        0.4371786   0.2902476   0.6247417</code></pre>
</div>
</div>
<p>The estimated slope indicates that a 1 cm increase in the length of the Yelloweye Rockfish will result in a 0.437 increase in the log odds that the Rockfish is mature. Changes in log odds are difficult to interpret. However, the back-transformed slope is interpreted as a multiplicative change in the odds of being mature. For example, a 1 cm increase in the length of the Yelloweye Rockfish will result in a 1.548 (i.e., <span class="math inline">\(e^{0.437}\)</span>) times increase in the odds that the Rockfish is mature.</p>
</section>
<section id="predicted-probability-of-being-mature" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="predicted-probability-of-being-mature">Predicted Probability of Being Mature</h2>
<p>The probability of a fish being mature given the observed value of the explanatory variable (<span class="math inline">\(x\)</span>) can be computed by solving <a href="#eq-LogisticModel">Equation&nbsp;1</a> for <span class="math inline">\(p\)</span>,</p>
<p><span id="eq-LogisticPredict"><span class="math display">\[ p = \frac{e^{\alpha + \beta_{1}x}}{1+e^{\alpha + \beta_{1}}}  \tag{2}\]</span></span></p>
<p>This prediction is computed with <code>predict()</code>, which requires the <code>glm()</code> object as the first argument, a data.frame with the values of the explanatory variable for which to make the prediction as the second argument, and <code>type="response"</code> (which forces the prediction of the probability, rather than the log odds, of being mature). For example, the predicted probabilities of being mature for female Yelloweye Rockfish that are 32- and 42-cm total length are computed below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(glm1,<span class="fu">data.frame</span>(<span class="at">length=</span><span class="fu">c</span>(<span class="dv">32</span>,<span class="dv">42</span>)),<span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|          1         2 
#R|  0.0493342 0.8042766</code></pre>
</div>
</div>
<div class="page-columns page-full"><p>Confidence intervals for the predicted probability are formed by computing the prediction for each bootstrap sample and then extracting the values for the upper and lower 2.5% of these predictions. This process is most easily accomplished by forming a function that represents <a href="#eq-LogisticPredict">Equation&nbsp;2</a> and then using <code>apply()</code> to apply that function to each row of the matrix containing the bootstrap samples. This is the same process as described in Chapter 12 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>. The code below computes the 95% confidence intervals for the predicted probability of being mature for 32 cm long Yelloweye Rockfish.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn3"><p><sup>3</sup>&nbsp;Note here that the results of each bootstrapped sample are in <code>t</code> of the <code>Boot()</code> object (i.e., <code>bcL</code>).</p></li></div></div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>predP <span class="ot">&lt;-</span> <span class="cf">function</span>(cf,x) <span class="fu">exp</span>(cf[<span class="dv">1</span>]<span class="sc">+</span>cf[<span class="dv">2</span>]<span class="sc">*</span>x)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(cf[<span class="dv">1</span>]<span class="sc">+</span>cf[<span class="dv">2</span>]<span class="sc">*</span>x))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>p32 <span class="ot">&lt;-</span> <span class="fu">apply</span>(bcL<span class="sc">$</span>t,<span class="dv">1</span>,predP,<span class="at">x=</span><span class="dv">32</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(p32,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|         2.5%       97.5% 
#R|  0.005181076 0.138317023</code></pre>
</div>
</div>
<p>Thus, the probability that a 32 cm Yelloweye Rockfish is mature is between 0.005 and 0.138.</p>
</section>
<section id="a-summary-plot" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="a-summary-plot">A Summary Plot</h2>
<p>A plot that illustrates the fit of the logistic regression (<a href="#fig-LogisticFit1">Figure&nbsp;2</a>) is constructed in several steps. First, a base plot that depicts the raw data is constructed. Take special note here that <code>maturity</code> is forced to be numeric between 0 and 1 for the plot and transparent points (as described in Chapter 3 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>) are used because there is considerable overplotting with the “discrete” maturity and length data.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>((<span class="fu">as.numeric</span>(maturity)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">~</span>length,<span class="at">data=</span>df,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="fu">rgb</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span><span class="sc">/</span><span class="dv">8</span>),</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Total Length (cm)"</span>,<span class="at">ylab=</span><span class="st">"Proportion Mature"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second, points that represent the proportion mature for each 2-cm length bin are added to the plot with <code>points()</code> (recall that the summaries in <code>props</code> were constructed above). Note that <code>pch=3</code> plots the points as “plus signs.”</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(props[,<span class="st">"Mature"</span>]<span class="sc">~</span><span class="fu">as.numeric</span>(<span class="fu">rownames</span>(props)),<span class="at">pch=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, the fitted line from the logistic regression is added by first using the <code>glm()</code> object to predict the probability of being mature for lengths that span the range of observed lengths and then plotting these values as a line with <code>lines()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>lens <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">30</span>,<span class="dv">70</span>,<span class="at">length.out=</span><span class="dv">199</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm1,<span class="fu">data.frame</span>(<span class="at">length=</span>lens),<span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(preds<span class="sc">~</span>lens,<span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full" data-layout-align="center" data-par1="true">
<div class="cell-output-display page-columns page-full">
<div id="fig-LogisticFit1" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="maturity_files/figure-html/fig-LogisticFit1-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption margin-caption">Figure&nbsp;2: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
</section>
<section id="length--or-age-at-maturity" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="length--or-age-at-maturity">Length- or Age-at-Maturity</h2>
<p>A common metric in fisheries science is to find the length or age at which a certain percentage of fish are mature. For example, it is common to ask “what is the length or age at which 50% of the fish have reached maturity?” A general formula for computing this metric is found by solving <a href="#eq-LogisticModel">Equation&nbsp;1</a> for <span class="math inline">\(X\)</span>,</p>
<p><span id="eq-LogisticReverseGnrl"><span class="math display">\[ x = \frac{log\left(\frac{p}{1-p}\right)-\alpha}{\beta_{1}}  \tag{3}\]</span></span></p>
<p>In the common case of finding <span class="math inline">\(X\)</span> for 50% maturity (i.e., <span class="math inline">\(p=0.5\)</span>), <a href="#eq-LogisticReverseGnrl">Equation&nbsp;3</a> reduces to</p>
<p><span id="eq-LogisticReverse50"><span class="math display">\[ x = -\frac{\alpha}{\beta_{1}}  \tag{4}\]</span></span></p>
<p>The age at which 50% of the fish are mature is commonly symbolized as <span class="math inline">\(A_{50}\)</span>. Similarly, the length at which 90% of the fish are mature would be <span class="math inline">\(L_{90}\)</span>.</p>
<p>These calculations are simplified by creating a function to perform <a href="#eq-LogisticReverseGnrl">Equation&nbsp;3</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lrPerc <span class="ot">&lt;-</span> <span class="cf">function</span>(cf,p) (<span class="fu">log</span>(p<span class="sc">/</span>(<span class="dv">1</span><span class="sc">-</span>p))<span class="sc">-</span>cf[[<span class="dv">1</span>]])<span class="sc">/</span>cf[[<span class="dv">2</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This functions takes the coefficents from the <code>glm()</code> object as the first argument and the probability of interest (<span class="math inline">\(p\)</span>) as the second argument. As examples, the lengths at which 50% and 90% of the female Yelloweye Rockfish are mature are computed below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>( L50 <span class="ot">&lt;-</span> <span class="fu">lrPerc</span>(<span class="fu">coef</span>(glm1),<span class="fl">0.5</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  [1] 38.76736</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>( L90 <span class="ot">&lt;-</span> <span class="fu">lrPerc</span>(<span class="fu">coef</span>(glm1),<span class="fl">0.9</span>) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  [1] 43.79328</code></pre>
</div>
</div>
<p>Confidence intervals for these values are constructed from the bootstrap samples, similar to what was illustrated above for predicted values.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>bL50 <span class="ot">&lt;-</span> <span class="fu">apply</span>(bcL<span class="sc">$</span>t,<span class="dv">1</span>,lrPerc,<span class="at">p=</span><span class="fl">0.5</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>( L50ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(bL50,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|      2.5%    97.5% 
#R|  37.33720 40.20835</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>bL90 <span class="ot">&lt;-</span> <span class="fu">apply</span>(bcL<span class="sc">$</span>t,<span class="dv">1</span>,lrPerc,<span class="at">p=</span><span class="fl">0.9</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>( L90ci <span class="ot">&lt;-</span> <span class="fu">quantile</span>(bL90,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|      2.5%    97.5% 
#R|  41.64754 45.78287</code></pre>
</div>
</div>
<p>Thus, for example, the predicted length at which 50% of the Yelloweye Rockfish are mature is between 37.3 and 40.2, with 95% confidence.</p>
<p>The calculation of the <span class="math inline">\(L_{50}\)</span> may be illustrated on a fitted-line plot (<a href="#fig-LogisticFit2">Figure&nbsp;3</a>) by adding the code below to the code used above to construct <a href="#fig-LogisticFit1">Figure&nbsp;2</a>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="dv">0</span>,L50),<span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(L50,L50),<span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.2</span>,<span class="fl">0.5</span>),<span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell page-columns page-full" data-layout-align="center" data-par1="true">
<div class="cell-output-display page-columns page-full">
<div id="fig-LogisticFit2" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="maturity_files/figure-html/fig-LogisticFit2-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption margin-caption">Figure&nbsp;3: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length with <span class="math inline">\(L_{50}\)</span> shown.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>&nbsp;</p>
</section>
</section>
<section id="modeling-with-summarized-data" class="level1 page-columns page-full">
<h1>Modeling with Summarized Data</h1>
<p>Sometimes maturity data is presented in summarized format – that is, the proportion of fish for each length that were mature. Such data can be computed from the original data.frame with the code below. Note that there are two “tricks” in this code. First, the <code>maturity</code> factor variable is coerced to be a numeric variable, but 1 is subtracted from this result because values of 1 for immature and 2 for mature are returned by <code>as.numeric()</code> when applied to a factor variable. Second, the mean of this result is the proportion of ones in the data, which is the proportion of mature fish.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(length) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">pmat=</span><span class="fu">mean</span>(<span class="fu">as.numeric</span>(maturity)<span class="sc">-</span><span class="dv">1</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n=</span><span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">headtail</span>(df2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|     length pmat n
#R|  1      31    0 1
#R|  2      32    0 4
#R|  3      33    0 2
#R|  33     67    1 1
#R|  34     68    1 1
#R|  35     70    1 1</code></pre>
</div>
</div>
<p>Also note that this code is only used here to produce data to illustrate how to analyze summarized data. If one has raw data, as in this supplement, then the methods of the previous section should be used, though the technique used here provides identical answers.</p>
<div class="page-columns page-full"><p>The appropriate logistic regression model is again fit with <code>glm()</code>. However, the left side of the formula is the proportion of “successes” variable and <code>weights=</code> is set equal to the sample size used to compute each proportion. Once the model is fit, the same extractor functions can be used to summarize the results.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn4"><p><sup>4</sup>&nbsp;<code>glm()</code> and <code>Boot()</code> will return warnings about non-integer number of successes when used in this way.</p></li></div></div>
<div class="cell" data-layout-align="center" data-hash="maturity_cache/html/unnamed-chunk-24_53e9e7cb747b0e1ef3d509d982a6ced1">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(pmat<span class="sc">~</span>length,<span class="at">data=</span>df2,<span class="at">family=</span>binomial,<span class="at">weights=</span>n)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>bcL2 <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">Boot</span>(glm2)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">Ests=</span><span class="fu">coef</span>(glm2),<span class="fu">confint</span>(bcL2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|                     Ests       2.5 %      97.5 %
#R|  (Intercept) -16.9482593 -25.6337952 -11.4019376
#R|  length        0.4371786   0.2980871   0.6561343</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(glm2,<span class="fu">data.frame</span>(<span class="at">length=</span><span class="fu">c</span>(<span class="dv">32</span>,<span class="dv">42</span>)),<span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|          1         2 
#R|  0.0493342 0.8042766</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>p32a <span class="ot">&lt;-</span> <span class="fu">apply</span>(bcL2<span class="sc">$</span>t,<span class="dv">1</span>,predP,<span class="at">x=</span><span class="dv">32</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(p32a,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|         2.5%       97.5% 
#R|  0.006303771 0.118633961</code></pre>
</div>
</div>
<p>Note that the coefficients and predictions computed here are the same as in the results from using the raw data. The bootstrapped confidence intervals differ slightly due to the inherent randomization used in bootstrap resampling (and because a small number of bootstrap samples were used to produce this supplement).</p>
<p>&nbsp;</p>
</section>
<section id="comparing-logistic-regressions-between-groups" class="level1 page-columns page-full">
<h1>Comparing Logistic Regressions Between Groups</h1>
<section id="model-fitting" class="level2">
<h2 class="anchored" data-anchor-id="model-fitting">Model Fitting</h2>
<p>It may be important to determine if the fit of the logistic regression differs between two groups. For example, one may need to determine if the logistic regression parameters differ significantly between fish captured “pre-2002” and those captured in “2002 and after” (recall that these two “eras” are recorded in <code>era</code> in <code>df</code>).</p>
<p>The model required to answer this type of question is a logistic regression version of the dummy variable regression introduced in Chapter 7 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>. Specifically, the right side of the formula in <code>glm()</code> is modified to be <code>quant*factor</code> where <code>quant</code> is the covariate (usually length or age) and <code>factor</code> is the factor variable that identifies the groups being compared. As noted in Chapter 7 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>, this formula is actually shorthand for a model with three terms – <code>quant</code> and <code>factor</code> main effects and the interaction between the <code>quant</code> and <code>factor</code> variables. In this case, the model is fit as shown below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>glm3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(maturity<span class="sc">~</span>length<span class="sc">*</span>era,<span class="at">data=</span>df,<span class="at">family=</span>binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The significance of terms in a general linear model are computed with a chi-square distribution and summarized in an “Analysis of Deviance Table”, rather than with an F distribution and ANOVA table as with a linear model. Fortunately, the Analysis of Deviance table using Type II tests is also retrieved with <code>Anova()</code> from <code>car</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(glm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  Analysis of Deviance Table (Type II tests)
#R|  
#R|  Response: maturity
#R|             LR Chisq Df Pr(&gt;Chisq)    
#R|  length       68.599  1    &lt; 2e-16 ***
#R|  era           0.005  1    0.94541    
#R|  length:era    3.100  1    0.07831 .  
#R|  ---
#R|  Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>As with the ANOVA table in a dummy variable regression, the Analysis of Deviance table should be read from the bottom. In this case, the interaction term is not signficant which suggests that the slopes for the logit-transformed models do not differ between the eras. The <code>era</code> main effect is also not signficant, which suggests that the y-intercepts for the logit-transformed models do not differ between the eras. Thus, there is no signficant difference in the logistic regressions between fish captured in the two eras.</p>
</section>
<section id="comparing-lengths--or-ages-at-maturity" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="comparing-lengths--or-ages-at-maturity">Comparing Lengths- or Ages-at-Maturity</h2>
<p>A p-value for testing whether the <span class="math inline">\(L_{50}\)</span> differed between groups may be computed from the bootstrapped samples. However, this calculation requires several steps and a good understanding of the parameter estimates from the logistic regression model fit to both groups. Thus, the steps and the parameter estimates are described further below.</p>
<p>Before building the hypothesis test, lets examine the parameter estimates for the logistic regression model.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(glm3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|               (Intercept)                   length        era2002 and after 
#R|               -27.1314345                0.6956840               14.0137840 
#R|  length:era2002 and after 
#R|                -0.3510082</code></pre>
</div>
</div>
<p>Note that the parameter estimates under the <code>(Intercept)</code> and <code>length</code> headings are the intercept and slope, respectively, for the “reference” group in the model. The reference group is the alphabetically first group, unless the levels of the factor variable were changed by the user as was done in this supplement. The order of the levels can be observed with <code>str()</code> or <code>levels()</code>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(df<span class="sc">$</span>era)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  [1] "pre-2002"       "2002 and after"</code></pre>
</div>
</div>
<p>Thus, the estimated intercept and slope of the logistic regression for the “pre-2002” era fish are -27.131 and 0.696, respectively.</p>
<p>The parameter estimates under the <code>era2002 and after</code> and <code>length:era2002 and after</code> are the <strong>differences</strong> in intercept and slope between the two eras. Thus, these values need to be added to the intercept and slope for the “pre-2000” era to estimate the intercept and slope for the “2002 and after” era. Thus, the estimated intercept and slope of the logistic regression for the “2002 and after” era fish are -13.118 and 0.345, respectively.</p>
<p>The first step in building the hypothesis test for whether <span class="math inline">\(L_{50}\)</span> differs between eras is to construct the bootstrap samples from the <code>glm()</code> object.</p>
<div class="cell" data-layout-align="center" data-hash="maturity_cache/html/unnamed-chunk-29_555e62b27a5810e207580e01c7e4f2ec">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>bcL3 <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">Boot</span>(glm3)  </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">headtail</span>(bcL3<span class="sc">$</span>t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|         (Intercept)    length era2002 and after length:era2002 and after
#R|  [1,]     -18.80167 0.4746840          6.963441               -0.1613036
#R|  [2,]     -23.72944 0.6336083         14.644565               -0.3923172
#R|  [3,]     -45.05273 1.1581163         25.728301               -0.6624715
#R|  [997,]   -27.95516 0.7594994         13.718180               -0.3952151
#R|  [998,]   -28.78888 0.7606613         20.036183               -0.5105222
#R|  [999,]   -34.05215 0.8546306         17.169055               -0.4233520</code></pre>
</div>
</div>
<p>The <span class="math inline">\(L_{50}\)</span> for fish from the “pre-2002” era is computed for each sample using only the first two columns of the bootstrap sample results (i.e., the intercept and slope for the “pre-2002” era) and the <code>lrperc()</code> function created and used in a previous section. The <span class="math inline">\(L_{50}\)</span> for fish from the “2002 and after” era is computed similarly but the last two columns in the bootstrap sample results must be added to the first two columns (i.e., produce the intercept and slope for the “2002 and after” era).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>L50.pre<span class="ot">=</span> <span class="fu">apply</span>(bcL3<span class="sc">$</span>t[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>],<span class="dv">1</span>,lrPerc,<span class="at">p=</span><span class="fl">0.5</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>L50.post<span class="ot">=</span><span class="fu">apply</span>(bcL3<span class="sc">$</span>t[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]<span class="sc">+</span>bcL3<span class="sc">$</span>t[,<span class="dv">3</span><span class="sc">:</span><span class="dv">4</span>],<span class="dv">1</span>,lrPerc,<span class="at">p=</span><span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If there was no difference in <span class="math inline">\(L_{50}\)</span> between the two eras, then one would expect the means of these two groups to be the same or, equivalently, the mean of the differences in these two value to equal zero. The difference in <span class="math inline">\(L_{50}\)</span> for each bootstrap sample is computed below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>L50.diff <span class="ot">&lt;-</span> L50.pre<span class="sc">-</span>L50.post</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="page-columns page-full"><p>A two-sided p-value may be computed as two times the smaller of the proportions of samples that are less than or greater than 0.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p><div class="no-row-height column-margin column-container"><li id="fn5"><p><sup>5</sup>&nbsp;This code exploits the fact that R treats a <code>TRUE</code> as a <code>1</code> and a <code>FALSE</code> as a <code>0</code> such that the mean of a vector of <code>TRUE</code>s and <code>FALSE</code>s will return the proportion of <code>TRUE</code>s.</p></li></div></div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>( p.L50.diff <span class="ot">&lt;-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">min</span>(<span class="fu">c</span>(<span class="fu">mean</span>(L50.diff<span class="sc">&gt;</span><span class="dv">0</span>),<span class="fu">mean</span>(L50.diff<span class="sc">&lt;</span><span class="dv">0</span>))) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|  [1] 0.5405405</code></pre>
</div>
</div>
<p>This result suggests that there is no significant difference in the <span class="math inline">\(L_{50}\)</span> for fish captured in the two eras (not surprising given that the logistic regression parameters did not differ between eras).</p>
<p>Confidence intervals for the difference in <span class="math inline">\(L_{50}\)</span> between the eras and the <span class="math inline">\(L_{50}\)</span> for each era may be computed as before but making sure to use the correct vector of results.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>( ci.L50.diff <span class="ot">&lt;-</span> <span class="fu">quantile</span>(L50.diff,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|       2.5%     97.5% 
#R|  -1.856107  4.625132</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>( ci.L50.pre <span class="ot">&lt;-</span>  <span class="fu">quantile</span>(L50.pre,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|      2.5%    97.5% 
#R|  37.25822 40.90922</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>( ci.L50.post <span class="ot">&lt;-</span> <span class="fu">quantile</span>(L50.post,<span class="fu">c</span>(<span class="fl">0.025</span>,<span class="fl">0.975</span>)) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre class="output"><code>#R|      2.5%    97.5% 
#R|  34.99124 40.29840</code></pre>
</div>
</div>
</section>
<section id="a-summary-plot-1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="a-summary-plot-1">A Summary Plot</h2>
<p>The construction of a plot that illustrates the fitted logistic regression lines for both groups is left largely as an exercise for the reader. Note that the code below uses several of the same ideas shown previously and relies on directions given in Chapter 3 of <span class="citation" data-cites="ogleIntroductoryFisheriesAnalyses2016">Ogle (<a href="#ref-ogleIntroductoryFisheriesAnalyses2016" role="doc-biblioref">2016</a>)</span>.</p>
<div class="cell page-columns page-full" data-layout-align="center" data-par1="true">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Set-up colors</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>clrs1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"black"</span>,<span class="st">"red"</span>)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>clrs2 <span class="ot">&lt;-</span> <span class="fu">col2rgbt</span>(clrs1,<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>)</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Get predicted values for each era</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>lvls <span class="ot">&lt;-</span> <span class="fu">levels</span>(df<span class="sc">$</span>era)</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>lens <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">30</span>,<span class="dv">70</span>,<span class="at">length.out=</span><span class="dv">99</span>)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>pa02 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm3,<span class="at">type=</span><span class="st">"response"</span>,</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>                <span class="fu">data.frame</span>(<span class="at">length=</span>lens,<span class="at">era=</span><span class="fu">factor</span>(<span class="st">"2002 and after"</span>,<span class="at">levels=</span>lvls)))</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>pp02 <span class="ot">&lt;-</span> <span class="fu">predict</span>(glm3,<span class="at">type=</span><span class="st">"response"</span>,</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>                <span class="fu">data.frame</span>(<span class="at">length=</span>lens,<span class="at">era=</span><span class="fu">factor</span>(<span class="st">"pre-2002"</span>,<span class="at">levels=</span>lvls)))</span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Make the base plot</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>((<span class="fu">as.numeric</span>(maturity)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">~</span>length,<span class="at">data=</span><span class="fu">filter</span>(df,era<span class="sc">==</span>lvls[<span class="dv">1</span>]),</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clrs2[<span class="dv">1</span>],<span class="at">xlab=</span><span class="st">"Total Length (cm)"</span>,<span class="at">ylab=</span><span class="st">"Proportion Mature"</span>)</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>((<span class="fu">as.numeric</span>(maturity)<span class="sc">-</span><span class="dv">1</span>)<span class="sc">~</span>length,<span class="at">data=</span><span class="fu">filter</span>(df,era<span class="sc">==</span>lvls[<span class="dv">2</span>]),</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span>clrs2[<span class="dv">2</span>])</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Add the two fitted lines</span></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(pa02<span class="sc">~</span>lens,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span>clrs1[<span class="dv">1</span>])</span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(pp02<span class="sc">~</span>lens,<span class="at">lwd=</span><span class="dv">2</span>,<span class="at">col=</span>clrs1[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div id="fig-LogisticFit3" class="quarto-figure quarto-figure-center anchored page-columns page-full">
<figure class="figure page-columns page-full">
<p><img src="maturity_files/figure-html/fig-LogisticFit3-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption margin-caption">Figure&nbsp;4: Fitted logistic regression for the proportion of female Yelloweye Rockfish that are mature by total length separated by the ‘pre-2002’ and ‘2002 and after’ eras.</figcaption><p></p>
</figure>
</div>
</div>
</div>



</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-ogleIntroductoryFisheriesAnalyses2016" class="csl-entry" role="doc-biblioentry">
Ogle, D. H. 2016. <a href="http://derekogle.com/IFAR/">Introductory <span>Fisheries</span> <span>Analyses</span> with <span>R</span></a>. CRC Press, Boca Raton, FL.
</div>
<div id="ref-pope_methods_2010" class="csl-entry" role="doc-biblioentry">
Pope, K. L., S. E. Lochmann, and M. K. Young. 2010. Methods for <span>Assessing</span> <span>Fish</span> <span>Populations</span>. Pages 325–351 <em>in</em> W. A. Hubert and M. C. Quist, editors. Inland <span>Fisheries</span> <span>Management</span> in <span>North</span> <span>America</span>Third. American Fisheries Society, Bethesda, MD.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp(/https:\/\/droglenc\.github\.io\/IFAR\//);
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
</div> <!-- /content -->



<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>