---
layout: page
title: Age Comparisons
subtitle: Lake Champlain Lake Whitefish
---

Herbst and Marsden (2011) compared the precision, bias, and reader uncertainty of ages estimated from the scales, dorsal fin rays, and otoliths of 151 Lake Whitefish (*Coregonus clupeaformis*) captured from Lake Champlain in 2009.  The inital age assessments for two readers and a consensus age between the two readers from each of the three structures (variables are the structure name with a "1" or "2" appended to denote the reader or "C" for the consensus ages) are in `data(WhitefishLC)` in `FSA`.

1. Use tabular, graphical, and statistical methods to describe any apparent bias between scale and otolith *consensus* age estimates.

1. Describe any apparent bias in otolith age estimates between the two readers.

1. Describe precision of otolith age estimates between the two readers.

1. Describe any apparent bias in scale age estimates between the two readers.

1. Describe precision of scales age estimates between the two readers.

1. Describe any apparent bias in fin ray and otolith *consensus* age estimates.

1. Describe any apparent bias in fin ray age estimates between the two readers.

1. Describe precision of fin ray age estimates between the two readers.

---
<p style="font-size:6px">from [Derek H. Ogle](http://derekogle.com), 23-Sep-15, updated 23-Sep15</p>
