---
layout: page
title: Individual Growth
subtitle: Lake Ontario Rock Bass A
author: Derek H. Ogle
output: 
  html_document: 
    fig_width: 5
    self_contained: no
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/IFAR/exercises")
source("../rhelpers/modHTML.R"); modHTML("LORockBass_Growth_A")
```

[Wolfert (1980)](https://pubs.er.usgs.gov/publication/1000461) measured the total length (TL) of 1288 Rock Bass (*Ambloplites rupestris*) from Eastern Lake Ontario in the late 1970s.  In addition, scales were removed for age estimation from as many as 10 specimens from each 10 mm length interval.  All data are recorded in [this CSV file](data/RockBassLO2.csv) (these data are also available in  `data(RockBassLO2)` from `FSAdata`) [Note: the filename contains an "oh" not a "zero."].

In this [age-length key exercise](ALK_LORockBass_B.html), a data.frame was produced that had age assignments for all 1288 fish.  Use that data.frame to answer the questions below (i.e., open and run your script from that exercise and then continue with an analysis for the questions below.)

1. Plot TL versus age.  Observe the "shape" of the data (do the results look linear or like a von Bertalanffy growth curve, is there an obvious asymptote, are young fish well represented, how variable are lengths within ages).
1. Fit the typical parameterization of the von Bertalanffy growth function (VBGF).
    1. How realistic do the point estimates of $L_{\infty}$, $K$, and $t_{0}$ seem?
    1. Write the typical VBGF with parameters replaced by their estimated values.
    1. Carefully interpret the meaning of each parameter.
    1. Construct 95% bootstrapped confidence intervals for each parameter.  Comment on the widths of these confidence intervals.  What explains this?
    1. Predict the mean TL, with 95% confidence interval, for an age-6 Rock Bass.  Comment on the width of this confidence interval.  What explains this?
    1. Plot TL versus age and superimpose the best-fit VBGF.  Comment on model fit.
    1. Construct a residual plot.  Comment on model fit.
    1. Compute the correlation between parameter values.  Comment.

[Continue with this data set here](LORockBass_Growth_B.html).

---
<p style="font-size: 0.75em; color: c6c6c6;">from <a href="http://derekogle.com">Derek H. Ogle</a>, 23-Sep-15, updated 1-Oct-15, <a href="mailto:fishr@derekogle.com?subject=Rock Bass Growth Exercise (A)">Comments/Suggestions</a></p>

<style type="text/css">
ol ol { list-style-type: lower-alpha; }
</style>
