---
layout: page
title: Abundance from Mark-Recapture Data
subtitle: Upper Niagara Springs Pond Rainbow Trout
author: Derek H. Ogle
output: 
  html_document: 
    fig_width: 5
    self_contained: no
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/IFAR/exercises")
source("../rhelpers/modHTML.R"); modHTML("MarkRecap_UNSPRainbowTrout")
```

Warren *et al.* (2004) examined the population of Rainbow Trout (*Oncorhynchus mykiss*) in the Upper Niagara Springs Pond in 2000.  Fish were captured at two times by using an electrofishing unit attached to a driftboat. The capture history of all fish examined in the two samples is in `RBTroutUNSP` in the `FSAdata` package.  Analyze these capture histories to answer the following questions.

1. Create a summary of the capture histories.
1. From your capture history summary assign values to each of $M$, $n$, and $m$.
1. Construct an appropriate population estimate, with a 95% confidence interval, for Upper Niagara Springs Pond Rainbow Trout in 2000.  Carefully interpret the results.
1. Which method did you use to construct the confidence interval?  Explain why you chose that method.

---
<p style="font-size: 0.75em; color: c6c6c6;">from <a href="http://derekogle.com">Derek H. Ogle</a>, 27-Sep-15, updated 27-Sep-15</p>

<style type="text/css">
ol ol { list-style-type: lower-alpha; }
</style>

