---
layout: page
title: Abundance from Mark-Recapture Data
subtitle: Hypothetical Capture Histories
author: Derek H. Ogle
output: 
  html_document: 
    fig_width: 5
    self_contained: no
---

```{r echo=FALSE}
source("../rhelpers/IFARhelpers.R")
```

The following is a summary of the capture histories for a hypothetical collection of 100 fish.  Use these results to find $n_{i}$, $m_{i}$, $R_{i}$, and $M_{i}$ for each sample to be used in the Schnabel multiple census method [Hint: Find $n_{i}$ and $m_{i}$ and then $R_{i}$ and $M_{i}$.]

```{r echo=FALSE}
tmp <- c(11,12,5,14,5,2,1,15,2,2,1,2,1,1,4,4,7,6,1,1,1,1,1)
names(tmp) <- c("00001;","00010;","00011;","00100;","00101;",
                "00110;","00111;","01000;","01001;","01010;",
                "01011;","01100;","01101;","01110;","10000;",
                "10001;","10010;","10100;","10110;","11000;",
                "11010;","11011;","11111;")
tmp
```

---
```{r echo=FALSE, results="asis"}
exercise_footer("MarkRecap_HypotheticalCapHist")
```
