---
layout: page
title: Mortality
subtitle: Lake Superior Lake Trout
author: Derek H. Ogle
output: 
  html_document: 
    fig_width: 5
    self_contained: no
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/IFAR/exercises")
source("../rhelpers/modHTML.R"); modHTML("Mortality_LSKBLakeTrout")
```

The population biology of Lake Superior Lake Trout (*Salvelinus namaycush*) prior to 1950 was examined in detail by [Sakagawa and Pycha (1971)](http://www.nrcresearchpress.com/doi/abs/10.1139/f71-011?journalCode=jfrbc).  In Table 1 of their paper, they presented the number of Lake Trout by age (from scales) collected in 4.5-inch mesh gillnets that were set between the Keweenaw Peninsula and Munising, MI in 1948. The numbers of Lake Trout caught for ages 3 to 14 were 5, 18, 21, 10, 45, 109, 95, 63, 42, 25, 13, and 4. Use these data to answer the questions below. 

1. Is this an example of a cross-sectional or longitudinal catch curve?
1. Plot log(catch) versus age.  Which ages best represent the descending portion of the catch curve?  Explain.
1. Using the regression method, find the following (with 95% confidence intervals):
    1. Instantaneous total mortality rate.
    1. Annual total mortality rate.
    1. Annual survival rate.
    
1. Using the Chapman-Robson method, find the following (with 95% confidence intervals):
    1. Instantaneous total mortality rate.
    1. Annual total mortality rate.
    1. Annual survival rate.

1. Mathematically show how to find $A$ from $Z$.

---
<p style="font-size: 0.75em; color: c6c6c6;">from <a href="http://derekogle.com">Derek H. Ogle</a>, 26-Sep-15, updated 27-Sep-15</p>

<style type="text/css">
ol ol { list-style-type: lower-alpha; }
</style>

