---
layout: page
title: Mortality
subtitle: Stannard Rock (Lake Superior) Lake Trout
author: Derek H. Ogle
output: 
  html_document: 
    fig_width: 5
    self_contained: no
---
```{r echo=FALSE, eval=FALSE}
# Renders an appropriate HTML file for the webpage
setwd("C:/aaaWork/Web/GitHub/IFAR/exercises")
source("../rhelpers/modHTML.R"); modHTML("Mortality_LSSRLakeTrout")
```

[Curtis (1990)](http://www.glsc.usgs.gov/publications/1990/688) examined the population dynamics related to the recovery of an offshore Lake Trout population near Stannard Rock, Lake Superior.  As part of this study, mortality rates were estimated from the relative abundance of Lake Trout longer than 43.2 cm.  Relative abundance was recorded as the catch-per-unit-effort (CPE) of each age group in each year expressed as the number of fish caught per 50,000 m of 114.3 mm mesh gillnet.  The results are shown in the table below.  [Note: (1) the values in the table have been rounded to integers; (2) values recorded as "tr" in the original paper were recorded as "0.5" in this table; and (3) the years of capture are not contiguous (there is a break between 1959 and 1963 and again between 1969 and 1973).]  Use these results to answer the following questions.

\begin{center}
  \begin{tabular}{c|ccccccccc}
\hline\hline
\widen{-2}{7}{} & \multicolumn{9}{c}{Age-Group} \\
\cline{2-10}
\widen{-2}{7}{Year} & VI & VII & VIII & IX & X & XI & XII & XIII & XIV \\
\hline
\widen{0}{5}{1959} & 64 & 219 & 241 & 121 & 33 & 9 & 1 & 0.5 & 1 \\
\widen{0}{5}{1963} & 129 & 339 & 331 & 192 & 70 & 16 & 0.5 & 0.5 & 0.5 \\
\widen{0}{0}{1964} & 149 & 524 & 515 & 201 & 63 & 18 & 2 & 0.5 & 0.5 \\
\widen{0}{0}{1965} & 75 & 379 & 501 & 328 & 133 & 39 & 11 & 1 & 0.5 \\
\widen{0}{0}{1966} & 149 & 488 & 459 & 172 & 64 & 22 & 5 & 0.5 & 0.5 \\
\widen{0}{0}{1967} & 63 & 368 & 287 & 130 & 55 & 19 & 6 & 0.5 & 0.5 \\
\widen{0}{0}{1968} & 50 & 215 & 259 & 141 & 55 & 18 & 5 & 1 & 0.5 \\
\widen{0}{0}{1969} & 45 & 150 & 153 & 76 & 23 & 6 & 0.5 & 0.5 & 0.5 \\
\widen{0}{5}{1973} & 101 & 759 & 1268 & 1116 & 491 & 141 & 40 & 4 & 0.5 \\
\widen{0}{0}{1974} & 151 & 733 & 1114 & 1092 & 571 & 163 & 50 & 9 & 5 \\
\widen{0}{0}{1975} & 109 & 901 & 1517 & 1606 & 1076 & 342 & 117 & 12 & 7 \\
\widen{0}{0}{1976} & 53 & 604 & 1204 & 1560 & 1146 & 396 & 156 & 18 & 10 \\
\widen{0}{0}{1977} & 157 & 867 & 1343 & 1410 & 1031 & 417 & 192 & 17 & 7 \\
\widen{0}{0}{1978} & 89 & 735 & 1307 & 1623 & 1150 & 445 & 198 & 18 & 14 \\
\widen{-2}{0}{1979} & 29 & 299 & 718 & 1268 & 1195 & 585 & 300 & 36 & 14 \\
\hline\hline
  \end{tabular}
\end{center}


1. What year-class of fish is represented by the 339 age-VII fish caught in 1963?
1. Identify the vectors of catches and ages that would be used to estimate the instantaneous total mortality rates for the following situations.
   1. For fish captured in 1963.
   1. For fish of the 1963 year-class.
   1. The *earliest* year-class that is **fully** represented for ages IX through XII.
   1. The *latest* year-class that is **fully** represented for ages IX through XII.

1. For the data in each vector created above.
   1. Identify whether these data represent a cross-sectional or longitudinal catch curve?
   1. Identify the descending limb of each catch-curve.  Explain your reasoning.
   1. Estimate, with 95% confidence interval, the instantaneous total mortality rate using the regression method.  Carefully interpret this result.
   1. Convert the point estimate from above to an annual rate.
   1. Estimate, with 95% confidence interval, the instantaneous total mortality rate using the Chapman-Robson method.  Carefully interpret this result.
   1. Convert the point estimate from above to an annual rate.

1. Determine if the instantaneous mortality rate is significantly different between the earliest and latest year-classes that are fully represented for ages IX through XII.

---
<p style="font-size: 0.75em; color: c6c6c6;">from <a href="http://derekogle.com">Derek H. Ogle</a>, 26-Sep-15, updated 27-Sep-15</p>

<style type="text/css">
ol ol { list-style-type: lower-alpha; }
</style>
